### ISSUE TITLE
How install this on windows ? 

### ISSUE THREAD

**Issue by Lethtel** [KiLMaN/T411-Torznab#15]
Hi guys,

Everything is in the tittle :p
How can i install this on windows ? 

Thanks for answers :)

**Comment by KiLMaN** [comment]
You need to install nodejs. It should work without problem after that.
I've not tested it. I will if you have any trouble 

Le 16 avr. 2016 14:16, à 14:16, Lethtel notifications@github.com a écrit:

**Comment by Lethtel** [comment]
Okay, thought it was specific to some nas or something like that.

After installing nodejs i was confronted to some "bug", but they are due to my comp' specifically :
Don't ask me why, but i couldn't change dir in my cmd.exe
The input "cp config.json.sample config.json" didn't work, but i just renamed the file myself.
and the server wanted to launch in "c:\windows\system32" even if i put a .bat directly in the right folder.

Finally i could get some result back from sonarr and download is working.

I'm just hoping my ratio will stay stable :o

Thank you =)

**Comment by nicecube** [comment]
Hi, i tried to run it on Windows, i installed node.js 
The npm install command was working no error
I start a cmd in admin and tried to run: node server.js
I got this error:

C:\T411-Torznab-master>node server.js
module.js:590
    throw err;
    ^

SyntaxError: C:\T411-Torznab-master\config.json: Unexpected token < in JSON at position 87
    at Object.parse (native)
    at Object.Module._extensions..json (module.js:587:27)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\T411-Torznab-master\server.js:5:14)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
 

Do i need to edit this to values in config.json : 
	"debugVerified":<debugVerified>,
	"onlyVerified":<onlyVerified>



**Edit: managed to get it start looking in the resolved issues:**

It's a error with the configuration file,
Please remove the two lines :

"debugVerified":<debugVerified>,
"onlyVerified":<onlyVerified>
and replace with :

"debugVerified":false,
"onlyVerified":true
It's an error with the default config file since we added docker .
